### ISSUE TITLE
Files missing when downloading from npm

### ISSUE THREAD

**Issue by thibmaek** [duivvv/generator-module-boilerplate#1]
Tried with `yarn global add generator-module-boilerplate` and `npm install -g generator-module-boilerplate`:
![screenshot 2016-11-11 08 00 59](https://cloud.githubusercontent.com/assets/6213695/20207179/b6fb447a-a7e5-11e6-90cd-7bb26b2fcbde.png)

Contents of directory in lib/node_modules/generator-module-boilerplate:
![screenshot 2016-11-11 08 07 11](https://cloud.githubusercontent.com/assets/6213695/20207200/dbe860f6-a7e5-11e6-8c39-d9dc269850b1.png)

**Comment by duivvv** [comment]
Ligt aan die package.json in m'n templates map. NPM upload enkel de files die in 'file' staan.

Moet die hernoemen naar _package.json in die map en terug naar package.json renamen bij copy. 

Tijd voor een PR?

**Comment by thibmaek** [comment]
Sure :) ik kijk er even naar.

**Comment by duivvv** [comment]
Misschien een _copyAndRename functie maken

**Comment by duivvv** [comment]
ik denk dat dit het meest elegant + herbruikbaar is

```js

const files = [
  `script.js`
  {from: `_package.json`, to: `package.json`}
]

```

en dan de copy functie aanpassen? (evt. https://lodash.com/docs/4.16.6#isPlainObject gebruiken)
