### ISSUE TITLE
Templates have incorrectly capitalized extensions, causing an error

### ISSUE THREAD

**Issue by nyurik** [duivvv/generator-module-boilerplate#33]
I just installed this package on Ubuntu 17.04 using

```bash
npm install yo -g
npm install generator-module-boilerplate -g
```
and ran `yo module-boilerplate` in an empty dir.  After all the questions, it crashed because `/home/yurik/.nvm/versions/node/v6.9.1/lib/node_modules/generator-module-boilerplate/generators/app/templates/.github/ISSUE_TEMPLATE.md` was not found.  Checking that dir I discovered that both `ISSUE_TEMPLATE.MD` and `PULL_REQUEST_TEMPLATE.MD` had their `.md` extension in the upper case.  Renaming them by hand made everything work ok.

**Comment by duivvv** [comment]
fixed :) thanks
