### ISSUE TITLE
Create sample unit test

### ISSUE THREAD

**Issue by nyurik** [duivvv/generator-module-boilerplate#34]
Different unit test frameworks use different style of test declaration. I think there should be a simple oneliner unit test generated as part of the boilerplate.  Thanks!

**Comment by duivvv** [comment]
any suggestions, or could you go more into detail?

**Comment by nyurik** [comment]
Not really - just something basic like  "describe / it / assert" ... To be honest, I am not the biggest fan of `jest`, as I am more used to the basic "assert.equals()", but that's a personal preference.

**Comment by duivvv** [comment]
fixed in https://github.com/duivvv/generator-module-boilerplate/pull/37
