### ISSUE TITLE
Still seeing errors when downloading from npm

### ISSUE THREAD

**Issue by thibmaek** [duivvv/generator-module-boilerplate#8]
Same as before: https://www.dropbox.com/s/d2ewphhakcrtwkz/Screenshot%202016-11-12%2019.27.07.png?dl=0

Wouldn't it just be easier to include them in the files in package.json? I think for the generator to work downloaded from npm, all the files starting with a dot would need to be prefixed no?

**Comment by duivvv** [comment]
denk dat dit enkel aan .gitignore en npm publish ligt, ga het oplossen met een rename

**Comment by duivvv** [comment]
npm negeert .gitignore blijkbaar 
https://github.com/npm/npm/issues/3763

fixed in de laatste npm versie, kan je nog een testen?

**Comment by duivvv** [comment]
lastig om te testen die generators

**Comment by duivvv** [comment]
@thibmaek

**Comment by thibmaek** [comment]
Nope nog steeds werkt het niet, getest op 3.10.9 wat de latest stable zou moeten zijn van npm
